frontend/controllers/DashboardController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Consultant;
use frontend\models\MailQueue;
use frontend\models\Message;
use frontend\models\Properties;
use frontend\models\Commissions;
use frontend\models\Clients;
use frontend\models\UsersContact;



/**
 * Site controller
 */
class DashboardController extends Controller
{
    /**
     * {@inheritdoc}
     */
	
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                   
                    [
                        
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
			'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
            
        ];
    }
	

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
		
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		$this->layout = 'dashboard';
		// All model instance
		$consultantModel = new Consultant();
		$mailModel = new MailQueue();
		$messageModel = new Message();
		$propertiesModel = new Properties();
		$commissionsModel = new Commissions();
		$clientsModel = new Clients();
		
		// Model instance implimentations
		
		$allDownlines = $consultantModel -> find()->where(['in','gen', yii::$app->user->identity->id])  -> count();
		
		$allSentEmail = $mailModel -> find()->where(['user_id' => yii::$app->user->identity->id]) -> andWhere(['>','attempts',0])  -> count();
		
		$allClients = $clientsModel -> find()->where(['consultant_id' => yii::$app->user->identity->id]) -> count();
		
		$allSentSms = $messageModel -> find()->where(['sender_user_id' => yii::$app->user->identity->id])   -> count();
		
		$allProperties = $propertiesModel -> find()->where(['status' => 0])   -> count();
		
		$allCommissions = $commissionsModel -> find()->where(['consultant_id' => yii::$app->user->identity->id])   -> count();
		
		return $this->render('index',[
			'totalGenerations' => $allDownlines,
			'totalEmails' => $allSentEmail,
			'totalSms' => $allSentSms,
			'totalProperties' => $allProperties,
			'totalCommissions' => $allCommissions,
			'totalClients' => $allClients,
		]);
        
    }
	
	/**
     * Displays all contacts of an individaul.
     *
     * @return mixed
     */
	public function actionUsersContact()
    {
		// All model instance
		$usersContacts = new UsersContact();
		
		$contactDetails = $usersContacts->find()->where(['user_id' => yii::$app->user->identity->id])->all();
	
		return $this->render('contacts',[
			'contactDetails' => $contactDetails,
			
		]);
        
    }
	
	public function actionUsersContactUpdate($id)
    {
		// All model instance
		$usersContacts = new UsersContact();
		$model = $usersContacts->findOne($id);
		if($model->load(Yii::$app->request->post())  && $model->save(false)){
			return 1;
		} else{
			return 0;
		}
		
    }
	
	public function actionUsersProfileUpdate()
    {
		// All model instance
		$usersProfile = new Consultant();
		$model = $usersProfile->findOne(['user_id' => yii::$app->user->identity->id]);
		if($model->load(Yii::$app->request->post())  && $model->save(false)){
			return 1;
		} else{
			return 0;
		}
		
    }
	
	public function actionUsersContactDelete($id)
    {
		// All model instance
		$usersContacts = new UsersContact();
		$model = $usersContacts->findOne($id);
		if($model->delete()){
			return 1;
		} else{
			return 0;
		}
		
    }
	
	public function actionProfile(){
		$model = new Consultant();
		$getConsultantDetails = $model->find()->select(['f_name','l_name','dob','phones','country','state','city','address','acc_name','bank','acc_num'])->where(['user_id' => yii::$app->user->identity->id])->asArray()->one();
		return $this->render('profile',[
			'profile' => $getConsultantDetails,
			'model' => $model,
			
		]);
		
	}

    
}

frontend/views/dashboard/contacts.php
<?
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\UsersContact;
?>
<? $this->title = 'Email and Phone numbers'; ?>
<?php $this->beginBlock('title') ?>
 <?= $this->title;?>
<?php $this->endBlock() ?>
<style>
	.formdisplay{
		display:none;
	}
	
	



#button {
	cursor:pointer;
	margin-top:20px;
	right:0;
	height:40px;
	padding-left:24px;
	padding-right:24px;
	font-family:Arial, Helvetica, sans-serif;
	font-weight:bold;
	font-size:20px;
	color:#FFF;
	text-shadow: 0px -1px 0px #000000;
	-webkit-border-radius:8px;
	border-radius:8px;
	border-top:1px solid #FFF;
	-webkit-box-shadow: 0px 2px 14px #000;
	box-shadow: 0px 2px 14px #000;
	background-color: #62add6;
	background-image:url(https://static.tumblr.com/maopbtg/ZHLmgtok7/button.png);
	background-repeat:repeat-x;
}
#button:active {
	zoom: 1;
	filter: alpha(opacity=80);
	opacity: 0.8;
}
#button:focus {
	zoom: 1;
	filter: alpha(opacity=80);
	opacity: 0.8;
}
	
	
	
.preloader-1 {
  
  width: 66px;
  height: 5px;
  display:none;
}






.preloader-1 .line {
  width: 3px;
  height: 5px;
  background: #fff;
  display: inline-block;
  animation: opacity-1 1000ms infinite ease-in-out;
}

.preloader-2 .line {
  width: 1px;
  height: 12px;
  background: #fff;
  margin: 0 1px;
  display: inline-block;
  animation: opacity-2 1000ms infinite ease-in-out;
}

.preloader-1 .line-1, .preloader-2 .line-1 { animation-delay: 800ms; }
.preloader-1 .line-2, .preloader-2 .line-2 { animation-delay: 600ms; }
.preloader-1 .line-3, .preloader-2 .line-3 { animation-delay: 400ms; }
.preloader-1 .line-4, .preloader-2 .line-4 { animation-delay: 200ms; }
.preloader-1 .line-6, .preloader-2 .line-6 { animation-delay: 200ms; }
.preloader-1 .line-7, .preloader-2 .line-7 { animation-delay: 400ms; }
.preloader-1 .line-8, .preloader-2 .line-8 { animation-delay: 600ms; }
.preloader-1 .line-9, .preloader-2 .line-9 { animation-delay: 800ms; }

@keyframes opacity-1 { 
  0% { 
    opacity: 1;
  }
  50% { 
    opacity: 0;
  }
  100% { 
    opacity: 1;
  }  
}

@keyframes opacity-2 { 
  0% { 
    opacity: 1;
    height: 15px;
  }
  50% { 
    opacity: 0;
    height: 12px;
  }
  100% { 
    opacity: 1;
    height: 15px;
  }  
}

</style>

<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title m-b-0">Emails</h5>
			</div>
			<table class="table table-striped">
				<thead>
					<tr>
					<th scope="col">#</th>
					<th scope="col">Name</th>
					<th scope="col">Email</th>
					<th scope="col">Phone</th>
					<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
					<? 
					$a = 1;
					foreach($contactDetails as $value){
						$usersContacts = new UsersContact();
						$model = $usersContacts->findOne($value->id);
					?>
					
							<tr data-id ="<?= $value->id; ?>">
								<?php $form = ActiveForm::begin(['action' => ['sms/sendsms'],'options' => ['class' => 'updatecontact']]); ?>
							  <th scope="row"><?=$a;?></th>
							  <td>
								  <div class="stringdisplay">
									  <?= $value-> name ;?>
									  
								  </div>
								  <div class="formdisplay">
									  
									  <?= $form->field($model, 'name')->textInput(['autofocus' => true,'id' => 'title'])->label(false); ?>
								  </div>
								</td>
							  <td>
								  <div class="stringdisplay">
									  <?= $value-> email;?>	
									  
								  </div>
								  <div class="formdisplay">
									  	
									  <?= $form->field($model, 'email')->textInput(['autofocus' => true,'id' => 'title'])->label(false); ?>
								  </div>
								</td>
							  <td>
								  <div class="stringdisplay">
									  <?= $value-> phone_number?>
									  
								  </div>
								  
								  <div class="formdisplay">
									  
									  <?= $form->field($model, 'phone_number')->textInput(['autofocus' => true,'id' => 'title'])->label(false); ?>
								  </div>
								</td>
							  <td>
								  <div class="formdisplay">
								  <?= Html::submitButton('<span id="sendtext class="senders" ">Send</span><span class="preloader-1">
								  <span>Loading</span>
								  <span class="line line-1"></span>
								  <span class="line line-2"></span>
								  <span class="line line-3"></span>
								  <span class="line line-4"></span>
								  <span class="line line-5"></span>

								  </span>', ['class' => 'btn btn-primary', 'name' => 'contact-button','id' => 'button']); ?>
								  </div>
								  <div class="stringdisplay">
								  <i class="fas fa-pencil-alt"></i>
								  |
								  <i class="far fa-trash-alt" data-del='<?= $value->id; ?>'></i>
								  </div>
							</td>
								<?php ActiveForm::end(); ?>
							</tr>
							<?$a++;?>
					
					<? } ?>                
				</tbody>           
			</table>            
		</div>            
	</div>            
</div>













<?php 
$url = Url::to(['dashboard/users-contact-update']);
$delUrl = Url::to(['dashboard/users-contact-delete']);
$invoiceform = <<<JS
$('.fa-pencil-alt').click(function(){
$(this).parent().parent().parent().find('.stringdisplay').hide()
 $(this).parent().parent().parent().find('.formdisplay').show()
 
})

$('.fa-trash-alt').click(function(){
	delId = $(this).data('del')
    $.post('$delUrl'+'&id='+delId)
    .always(function(result){
	
	res = result.split(" ");
   if(res[0] =='OK'){
   	$('.preloader-1').hide();
	   $('#sendtext').show().text('SMS have been sent and you made use of '+res[1]+' unit');
		
	
	
    }else{
    
		$('#sendtext').show().text('somthing went wrong and sms did not deliver');
		$('.preloader-1').hide();
	
    }
    }).fail(function(){
    console.log('Server Error');
    });
 
 
})

$('.table').DataTable();

$('.updatecontact').on('beforeSubmit', function (e) {
alert(12345)
	$('#sendtext').hide();
	$(this).parent().find('.preloader-1').show();
    var \$form = $(this);
	id = $(this).parent().data('id');
    $.post('$url'+'&id='+id,\$form.serialize())
    .always(function(result){
	
	res = result.split(" ");
   if(res[0] =='OK'){
   	$('.preloader-1').hide();
	   $('#sendtext').show().text('SMS have been sent and you made use of '+res[1]+' unit');
		
	
	
    }else{
    
		$('#sendtext').show().text('somthing went wrong and sms did not deliver');
		$('.preloader-1').hide();
	
    }
    }).fail(function(){
    console.log('Server Error');
    });
	
	setTimeout(function(){ 
	
		$('#sendtext').show().text('Send');
		\$form.reset();

	}, 5000);
    return false;
    
    
});
JS;
 
$this->registerJs($invoiceform);
?>

frontend/views/dashboard/index.php
<?
use yii\helpers\Url;
?>
<? $this->title = 'Dashboard'; ?>
<?php $this->beginBlock('title') ?>
<?= $this->title;?>
<?php $this->endBlock() ?>
<div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Sales Cards  -->
                <!-- ============================================================== -->
                <div class="row">
                    <!-- Column -->
                    <div class="col-md-6 col-lg-2 col-xlg-3">
						<a href="<?=Url::to(['/email'])?>">
                        	<div class="card card-hover">
                            <div class="box bg-cyan text-center">
                                <h1 class="font-light text-white"><i class="mdi mdi-email"></i></h1>
                                <h6 class="text-white">email</h6>
                            </div>
                        </div>
						</a>
                    </div>
                    <!-- Column -->
                    <div class="col-md-6 col-lg-2 col-xlg-3">
						<a href="<?=Url::to(['/generation'])?>">
                        	<div class="card card-hover">
                            <div class="box bg-success text-center">
                                <h1 class="font-light text-white"><i class="fa fa-users"></i></h1>
                                <h6 class="text-white">Team Members </h6>
                            </div>
                        </div>
						</a>
                    </div>
					
					<div class="col-md-6 col-lg-2 col-xlg-3">
						<a href="<?=Url::to(['/sms'])?>">
							<div class="card card-hover">
								<div class="box bg-danger text-center">
									<h1 class="font-light text-white"><i class="mdi mdi-message-reply"></i></h1>
									<h6 class="text-white">Sms</h6>
								</div>
							</div>
						</a>
                    </div>
                     <!-- Column -->
                    <div class="col-md-6 col-lg-2 col-xlg-3">
						<a href="<?=Url::to(['/properties'])?>">
                        	<div class="card card-hover">
                            <div class="box bg-warning text-center">
                                <h1 class="font-light text-white"><i class="mdi mdi-home-modern"></i></h1>
                                <h6 class="text-white">Properties</h6>
                            </div>
                        </div>
						</a>
                    </div>
                    <!-- Column -->
                    <div class="col-md-6 col-lg-2 col-xlg-3">
						<a href="<?=Url::to(['/transactions'])?>">
							<div class="card card-hover">
								<div class="box bg-danger text-center">
									<h1 class="font-light text-white"><i class="mdi mdi-cash-multiple"></i></h1>
									<h6 class="text-white">transactions</h6>
								</div>
							</div>
						</a>
                    </div>
                    <!-- Column -->
                    <div class="col-md-6 col-lg-2 col-xlg-3">
						<a href="<?=Url::to(['/clients'])?>">
                        	<div class="card card-hover">
                            <div class="box bg-info text-center">
                                <h1 class="font-light text-white"><i class="mdi mdi-briefcase"></i></h1>
                                <h6 class="text-white">Clients</h6>
                            </div>
                        </div>
						</a>
                    </div>
                    <!-- Column -->
                    <!-- Column -->
                    
                    <!-- Column -->
                </div>
                <!-- ============================================================== -->
                <!-- Sales chart -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-md-flex align-items-center">
                                    <div>
                                        <h4 class="card-title">Mothly Downline Analysis</h4>
                                        <h5 class="card-subtitle">Overview of Latest Month</h5>
                                    </div>
                                </div>
                                <div class="row">
                                    <!-- column -->
                                    <div class="col-lg-9">
                                        <div class="flot-chart">
                                            <div class="flot-chart-content" id="flot-line-chart"></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="row">
                                            <div class="col-6">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="mdi mdi-email m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5"><?= $totalEmails; ?></h5>
                                                   <small class="font-light">Total email</small>
                                                </div>
                                            </div>
                                             <div class="col-6">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="fa fa-users m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5"><?= $totalGenerations;?></h5>
                                                   <small class="font-light">total team</small>
                                                </div>
                                            </div>
                                            <div class="col-6 m-t-15">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="mdi mdi-message-reply m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5"><?= $totalSms;?></h5>
                                                   <small class="font-light">Total sms</small>
                                                </div>
                                            </div>
                                             <div class="col-6 m-t-15">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="mdi mdi-home-modern m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5"><?= $totalProperties;?></h5>
                                                   <small class="font-light">Total properties</small>
                                                </div>
                                            </div>
                                            <div class="col-6 m-t-15">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="mdi mdi-cash-multiple m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5"><?= $totalCommissions;?></h5>
                                                   <small class="font-light">transactions</small>
                                                </div>
                                            </div>
                                            <div class="col-6 m-t-15">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="mdi mdi-briefcase m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5"><?= $totalClients;?></h5>
                                                   <small class="font-light">clients</small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- column -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>

frontend/views/dashboard/profile.php
<?
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\UsersContact;
$models = $model->find()->where(['user_id'=> yii::$app->user->identity->id])->one();
?>
<? $this->title = 'Email and Phone numbers'; ?>
<?php $this->beginBlock('title') ?>
 <?= $this->title;?>
<?php $this->endBlock() ?>
<style>
	.formdisplay{
		display:none;
	}
	
	



#button {
	cursor:pointer;
	margin-top:20px;
	right:0;
	height:40px;
	padding-left:24px;
	padding-right:24px;
	font-family:Arial, Helvetica, sans-serif;
	font-weight:bold;
	font-size:20px;
	color:#FFF;
	text-shadow: 0px -1px 0px #000000;
	-webkit-border-radius:8px;
	border-radius:8px;
	border-top:1px solid #FFF;
	-webkit-box-shadow: 0px 2px 14px #000;
	box-shadow: 0px 2px 14px #000;
	background-color: #62add6;
	background-image:url(https://static.tumblr.com/maopbtg/ZHLmgtok7/button.png);
	background-repeat:repeat-x;
}
#button:active {
	zoom: 1;
	filter: alpha(opacity=80);
	opacity: 0.8;
}
#button:focus {
	zoom: 1;
	filter: alpha(opacity=80);
	opacity: 0.8;
}
	
	
	
.preloader-1 {
  
  width: 66px;
  height: 5px;
  display:none;
}






.preloader-1 .line {
  width: 3px;
  height: 5px;
  background: #fff;
  display: inline-block;
  animation: opacity-1 1000ms infinite ease-in-out;
}

.preloader-2 .line {
  width: 1px;
  height: 12px;
  background: #fff;
  margin: 0 1px;
  display: inline-block;
  animation: opacity-2 1000ms infinite ease-in-out;
}

.preloader-1 .line-1, .preloader-2 .line-1 { animation-delay: 800ms; }
.preloader-1 .line-2, .preloader-2 .line-2 { animation-delay: 600ms; }
.preloader-1 .line-3, .preloader-2 .line-3 { animation-delay: 400ms; }
.preloader-1 .line-4, .preloader-2 .line-4 { animation-delay: 200ms; }
.preloader-1 .line-6, .preloader-2 .line-6 { animation-delay: 200ms; }
.preloader-1 .line-7, .preloader-2 .line-7 { animation-delay: 400ms; }
.preloader-1 .line-8, .preloader-2 .line-8 { animation-delay: 600ms; }
.preloader-1 .line-9, .preloader-2 .line-9 { animation-delay: 800ms; }

@keyframes opacity-1 { 
  0% { 
    opacity: 1;
  }
  50% { 
    opacity: 0;
  }
  100% { 
    opacity: 1;
  }  
}

@keyframes opacity-2 { 
  0% { 
    opacity: 1;
    height: 15px;
  }
  50% { 
    opacity: 0;
    height: 12px;
  }
  100% { 
    opacity: 1;
    height: 15px;
  }  
}

</style>

<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title m-b-0">Emails</h5>
			</div>
			<table class="table table-striped">
				
				<tbody>
					<? 
					$a = 1;

					foreach($profile as $key =>  $value){
						
					?>
					
							<tr data-id ="<?= $value; ?>">
								
							  <th scope="row"><?= $key;?> :</th>
							  <td>
								  <?php $form = ActiveForm::begin(['action' => ['dashboard/users-profile-update'],'options' => ['class' => 'updateprofile']]); ?>
								  <div class="stringdisplay">
									   <?= !empty($value)?$value:'No value set';?>
									  
								  </div>
								  <div class="formdisplay">
									  
									  <?= $form->field($models, $key)->textInput(['autofocus' => true,'id' => 'title'])->label(false); ?>
								  </div>
								  
								  <div class="formdisplay">
								  <?= Html::submitButton('<span id="sendtext" class="senders" >Send</span><span class="preloader-1">
								  <span>Updating</span>
								  <span class="line line-1"></span>
								  <span class="line line-2"></span>
								  <span class="line line-3"></span>
								  <span class="line line-4"></span>
								  <span class="line line-5"></span>

								  </span>', ['class' => 'btn btn-primary', 'name' => 'contact-button','id' => 'button']); ?>
								  </div>
								  
								  <?php ActiveForm::end(); ?>
								</td>
							 
							  <td>
								  
								  <div class="stringdisplay">
								  <i class="fas fa-pencil-alt"></i>
								  
								  </div>
							</td>
								
							</tr>
							<?$a++;?>
					
					<? } ?>                
				</tbody>           
			</table>            
		</div>            
	</div>            
</div>













<?php 
$url = Url::to(['dashboard/users-profile-update']);
$delUrl = Url::to(['dashboard/users-contact-delete']);
$invoiceform = <<<JS
$('.fa-pencil-alt').click(function(){
$(this).parent().parent().parent().find('.stringdisplay').hide()
 $(this).parent().parent().parent().find('.formdisplay').show()
 
})



$('.updateprofile').on('beforeSubmit', function (e) {
	$('.senders').hide();
	$(this).parent().find('.preloader-1').show();
    var \$form = $(this);
	id = $(this).parent().data('id');
    $.post('$url'+'&id='+id,\$form.serialize())
    .always(function(result){
	
	
   if(result == 1){
   	$('.preloader-1').hide();
	$('.senders').show();
	$('.senders').show().text('Profile have been updated');
		
	
	
    }else{
    
		$('.senders').show().text('somthing went wrong and sms did not deliver');
		$('.preloader-1').hide();
	
    }
    }).fail(function(){
    console.log('Server Error');
    });
	
	setTimeout(function(){ 
	
		$('.senders').show().text('Send');
		$(document).find('.stringdisplay').show()
 		$(document).find('.formdisplay').hide()
		

	}, 5000);
    return false;
    
    
});
JS;
 
$this->registerJs($invoiceform);
?>